### ISSUE TITLE
Loss bi-direction connection when client try to reconnect to the server

### ISSUE THREAD

**Issue by banlong** [cenkalti/rpc2#12]
Server cannot reconnect to a client when I client reconnect to it. The result is the client can call server method but server cannot call method that handled by the clients (in other word, one way connection only, direction from client to the server).
![1](https://cloud.githubusercontent.com/assets/10793997/14234569/f100ae8e-f99a-11e5-85e5-1720a8a47081.png)

**Comment by cenkalti** [comment]
Server has the listener and client must connect to it. Other way is not possible. Communication is bi-directional once the connection is established. This is how this library works.
