### ISSUE TITLE
Add DebugLog configuration variable

### ISSUE THREAD

**Issue by montanaflynn** [cenkalti/rpc2#16]
When the server goes offline I'm getting these in my production environment which I would rather not have printed. I'm already catching the error and logging it in JSON format which I can then parse correctly.

```
2018/07/27 10:03:24 rpc2: client protocol error: unexpected EOF
{"level":"error","msg":"unexpected EOF","time":"2018-07-27T10:03:24+07:00"}
```

I don't think any package should do logging or at least have a flag to turn it off.

The official Golang rpc package does this: [net/rpc/client.go#L166](https://github.com/golang/go/blob/master/src/net/rpc/client.go#L166)

**Comment by cenkalti** [comment]
@montanaflynn Does this work? https://github.com/cenkalti/rpc2/pull/17

**Comment by montanaflynn** [comment]
@cenkalti yes, thanks!
