### ISSUE TITLE
Non array parameters not accepted when using JSONRPC

### ISSUE THREAD

**Issue by plaili** [cenkalti/rpc2#29]
At the moment array parameters are enforced. That's fine as long as we use rpc2 for both client and server, but other JSONRPC libraries do not enforce it and thus requests are not properly handled.

**Comment by plaili** [comment]
I'd be willing to work on that but based on your fix for #6 it sounds like it would be a bigger change, correct?

**Comment by cenkalti** [comment]
Yes, it is a bigger work but if you can find a way to solve it without breaking backwards compatibility I'll happily merge it.

**Comment by cenkalti** [comment]
See #31
