### ISSUE TITLE
Responses should include either result or error not both

### ISSUE THREAD

**Issue by plaili** [cenkalti/rpc2#30]
According to https://www.jsonrpc.org/specification#response_object:
"
result
This member is REQUIRED on success.
This member MUST NOT exist if there was an error invoking the method.
The value of this member is determined by the method invoked on the Server.
error
This member is REQUIRED on error.
This member MUST NOT exist if there was no error triggered during invocation.
The value for this member MUST be an Object as defined in section 5.1.
"

**Comment by cenkalti** [comment]
I think it can be fixed by adding `omitempty` to struct tags.

**Comment by cenkalti** [comment]
https://www.jsonrpc.org/specification_v1
