### ISSUE TITLE
Tests attempt to bind to same IP/port

### ISSUE THREAD

**Issue by gibmat** [cenkalti/rpc2#39]
Both of the tests (TestTCPGOB and TestJSONRPC) attempt to bind to the same IP/port: 127.0.0.1:5000. This works fine if the tests are run individually, but if run in parallel there is a race condition that one test may try to concurrently bind to an already-in-use port and fail.

Changing the port used by one of the tests to something different, like 5001, resolves this issue.

(Seen on a [Debian builder](https://buildd.debian.org/status/fetch.php?pkg=golang-github-cenkalti-rpc2&arch=all&ver=1.0.0-2&stamp=1703883048&raw=0) while packaging this library for use.)

**Comment by cenkalti** [comment]
Thanks for reporting @gibmat . I have fixed this issue in v1.0.1 .
