### ISSUE TITLE
can one client call another clients func. like the clients reg the function to  server. 

### ISSUE THREAD

**Issue by welldonexing** [cenkalti/rpc2#42]
can one client call another clients func. like the clients register the function to  server. 
test code like :
```
package main

import (
	"fmt"
	"net"

	"github.com/cenkalti/rpc2"
)

type Args struct{ A, B int }
type Reply int

func main() {
	srv := rpc2.NewServer()
	srv.Handle("add", func(client *rpc2.Client, args *Args, reply *Reply) error {

		// Reversed call (server to client)
		var rep Reply
		client.Call("mult", Args{2, 3}, &rep)
		fmt.Println("mult result:", rep)

		*reply = Reply(args.A + args.B)
		return nil
	})

	lis, _ := net.Listen("tcp", "127.0.0.1:5000")
	srv.Accept(lis)
}
```

the server dont change,  the client code is 
```
package main

import (
	"fmt"
	"net"

	"github.com/cenkalti/rpc2"
)

type Args struct{ A, B int }
type Reply int

func main() {
	conn, _ := net.Dial("tcp", "127.0.0.1:5000")

	clt := rpc2.NewClient(conn)
	clt.Handle("mult", func(client *rpc2.Client, args *Args, reply *Reply) error {
		*reply = Reply(args.A * args.B)
		return nil
	})
	go clt.Run()

	var rep Reply
	clt.Call("add", Args{1, 2}, &rep)
	fmt.Println("add result:", rep)

	conn2, _ := net.Dial("tcp", "127.0.0.1:5000")
	clt2 := rpc2.NewClient(conn2)
	go clt2.Run()
	var rep2 Reply
	clt.Call("mult", Args{1, 2}, &rep2)
	fmt.Println("mult result:", rep2)

}
```

in this code  , we create two clients, and the second clinet  call   the  "mult” from  first client  , it didnt  work.

why this ?   because in the server, we dont want to change the code   again and again.
but in my computer, we dont have gobal ip ,  so  , we want something connect to server, then create a new function, and
can be call by user. and the code is working local.  the server just a gateway.that is what i think about.

**Comment by cenkalti** [comment]
This library is not suitable for the use case you're describing out of the box. You'll have to write some code to achieve that. I recommend looking into the libraries in messaging category here: https://github.com/avelino/awesome-go?tab=readme-ov-file#messaging
